name: Reusable Workflow Test

on:
  workflow_call:

jobs:
  handle_event:
    name: ${{ github.event_name }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Handle webhook event..."
          echo "Action Path: $GITHUB_ACTION_PATH"
          echo "pwd"
          pwd
          echo "ls"
          ls
          echo "RECURSE"
          echo ls -R
          echo "ACTION PATH LS"
          cd $GITHUB_ACTION_PATH
          ls

          cd $GITHUB_ACTION_PATH/src
          echo "$GITHUB_PAYLOAD" > ./github_payload.json
          go run . ./github_payload.json
        shell: bash
